<?php

/**
 * @file
 * CRM Login module file.
 */

/**
 * Implements hook_preprocess_page().
 */
function crm_login_preprocess_page(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name === 'crm_login.login') {
    // Remove page title
    $variables['page']['#title'] = '';
    // Add body class
    $variables['attributes']['class'][] = 'page-auth';
    $variables['attributes']['class'][] = 'path-login';
  }
}
