#!/bin/bash

###############################################################################
# Script: fix_pipeline_view.sh
# Purpose: Fix Pipeline Kanban view field configuration
# Issue: Field is unknown - field_stage not properly configured
# Author: DevOps Team
# Date: 2026-02-26
###############################################################################

echo "========================================="
echo "Fixing Pipeline Kanban View"
echo "========================================="

ddev drush php-eval '
$view_id = "pipeline";

// Delete existing view
$view = \Drupal::entityTypeManager()->getStorage("view")->load($view_id);
if ($view) {
  echo "⚠️  Deleting existing view...\n";
  $view->delete();
}

// Create pipeline kanban view with proper field configuration
$view = \Drupal\views\Entity\View::create([
  "id" => $view_id,
  "label" => "Pipeline",
  "description" => "Deal pipeline kanban board",
  "tag" => "CRM",
  "base_table" => "node_field_data",
  "display" => [
    "default" => [
      "id" => "default",
      "display_plugin" => "default",
      "display_title" => "Default",
      "position" => 0,
      "display_options" => [
        "title" => "Pipeline",
        "fields" => [
          "field_stage" => [
            "id" => "field_stage",
            "table" => "node__field_stage",
            "field" => "field_stage",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "field",
            "label" => "",
            "exclude" => TRUE,
            "alter" => [
              "alter_text" => FALSE,
              "text" => "",
              "make_link" => FALSE,
              "path" => "",
              "absolute" => FALSE,
              "external" => FALSE,
              "replace_spaces" => FALSE,
              "path_case" => "none",
              "trim_whitespace" => FALSE,
              "alt" => "",
              "rel" => "",
              "link_class" => "",
              "prefix" => "",
              "suffix" => "",
              "target" => "",
              "nl2br" => FALSE,
              "max_length" => 0,
              "word_boundary" => TRUE,
              "ellipsis" => TRUE,
              "more_link" => FALSE,
              "more_link_text" => "",
              "more_link_path" => "",
              "strip_tags" => FALSE,
              "trim" => FALSE,
              "preserve_tags" => "",
              "html" => FALSE,
            ],
            "element_type" => "",
            "element_class" => "",
            "element_label_type" => "",
            "element_label_class" => "",
            "element_label_colon" => FALSE,
            "element_wrapper_type" => "",
            "element_wrapper_class" => "",
            "element_default_classes" => TRUE,
            "empty" => "",
            "hide_empty" => FALSE,
            "empty_zero" => FALSE,
            "hide_alter_empty" => TRUE,
            "type" => "entity_reference_label",
            "settings" => [
              "link" => FALSE,
            ],
          ],
          "title" => [
            "id" => "title",
            "table" => "node_field_data",
            "field" => "title",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "entity_type" => "node",
            "entity_field" => "title",
            "plugin_id" => "field",
            "label" => "",
            "exclude" => FALSE,
            "alter" => [
              "alter_text" => FALSE,
              "text" => "",
              "make_link" => FALSE,
              "path" => "",
              "absolute" => FALSE,
              "external" => FALSE,
              "replace_spaces" => FALSE,
              "path_case" => "none",
              "trim_whitespace" => FALSE,
              "alt" => "",
              "rel" => "",
              "link_class" => "",
              "prefix" => "",
              "suffix" => "",
              "target" => "",
              "nl2br" => FALSE,
              "max_length" => 0,
              "word_boundary" => TRUE,
              "ellipsis" => TRUE,
              "more_link" => FALSE,
              "more_link_text" => "",
              "more_link_path" => "",
              "strip_tags" => FALSE,
              "trim" => FALSE,
              "preserve_tags" => "",
              "html" => FALSE,
            ],
            "element_type" => "",
            "element_class" => "",
            "element_label_type" => "",
            "element_label_class" => "",
            "element_label_colon" => FALSE,
            "element_wrapper_type" => "",
            "element_wrapper_class" => "",
            "element_default_classes" => TRUE,
            "empty" => "",
            "hide_empty" => FALSE,
            "empty_zero" => FALSE,
            "hide_alter_empty" => TRUE,
            "type" => "string",
            "settings" => [
              "link_to_entity" => TRUE,
            ],
          ],
          "field_amount" => [
            "id" => "field_amount",
            "table" => "node__field_amount",
            "field" => "field_amount",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "field",
            "label" => "Amount",
            "exclude" => FALSE,
            "alter" => [
              "alter_text" => FALSE,
              "text" => "",
              "make_link" => FALSE,
              "path" => "",
              "absolute" => FALSE,
              "external" => FALSE,
              "replace_spaces" => FALSE,
              "path_case" => "none",
              "trim_whitespace" => FALSE,
              "alt" => "",
              "rel" => "",
              "link_class" => "",
              "prefix" => "",
              "suffix" => "",
              "target" => "",
              "nl2br" => FALSE,
              "max_length" => 0,
              "word_boundary" => TRUE,
              "ellipsis" => TRUE,
              "more_link" => FALSE,
              "more_link_text" => "",
              "more_link_path" => "",
              "strip_tags" => FALSE,
              "trim" => FALSE,
              "preserve_tags" => "",
              "html" => FALSE,
            ],
            "element_type" => "",
            "element_class" => "",
            "element_label_type" => "",
            "element_label_class" => "",
            "element_label_colon" => TRUE,
            "element_wrapper_type" => "",
            "element_wrapper_class" => "",
            "element_default_classes" => TRUE,
            "empty" => "",
            "hide_empty" => FALSE,
            "empty_zero" => FALSE,
            "hide_alter_empty" => TRUE,
            "type" => "number_decimal",
            "settings" => [
              "thousand_separator" => ",",
              "decimal_separator" => ".",
              "scale" => 2,
              "prefix_suffix" => TRUE,
            ],
          ],
          "field_contact" => [
            "id" => "field_contact",
            "table" => "node__field_contact",
            "field" => "field_contact",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "field",
            "label" => "Contact",
            "exclude" => FALSE,
            "alter" => [
              "alter_text" => FALSE,
              "text" => "",
              "make_link" => FALSE,
              "path" => "",
              "absolute" => FALSE,
              "external" => FALSE,
              "replace_spaces" => FALSE,
              "path_case" => "none",
              "trim_whitespace" => FALSE,
              "alt" => "",
              "rel" => "",
              "link_class" => "",
              "prefix" => "",
              "suffix" => "",
              "target" => "",
              "nl2br" => FALSE,
              "max_length" => 0,
              "word_boundary" => TRUE,
              "ellipsis" => TRUE,
              "more_link" => FALSE,
              "more_link_text" => "",
              "more_link_path" => "",
              "strip_tags" => FALSE,
              "trim" => FALSE,
              "preserve_tags" => "",
              "html" => FALSE,
            ],
            "element_type" => "",
            "element_class" => "",
            "element_label_type" => "",
            "element_label_class" => "",
            "element_label_colon" => TRUE,
            "element_wrapper_type" => "",
            "element_wrapper_class" => "",
            "element_default_classes" => TRUE,
            "empty" => "",
            "hide_empty" => FALSE,
            "empty_zero" => FALSE,
            "hide_alter_empty" => TRUE,
            "type" => "entity_reference_label",
            "settings" => [
              "link" => TRUE,
            ],
          ],
          "field_organization" => [
            "id" => "field_organization",
            "table" => "node__field_organization",
            "field" => "field_organization",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "field",
            "label" => "Organization",
            "exclude" => FALSE,
            "alter" => [
              "alter_text" => FALSE,
              "text" => "",
              "make_link" => FALSE,
              "path" => "",
              "absolute" => FALSE,
              "external" => FALSE,
              "replace_spaces" => FALSE,
              "path_case" => "none",
              "trim_whitespace" => FALSE,
              "alt" => "",
              "rel" => "",
              "link_class" => "",
              "prefix" => "",
              "suffix" => "",
              "target" => "",
              "nl2br" => FALSE,
              "max_length" => 0,
              "word_boundary" => TRUE,
              "ellipsis" => TRUE,
              "more_link" => FALSE,
              "more_link_text" => "",
              "more_link_path" => "",
              "strip_tags" => FALSE,
              "trim" => FALSE,
              "preserve_tags" => "",
              "html" => FALSE,
            ],
            "element_type" => "",
            "element_class" => "",
            "element_label_type" => "",
            "element_label_class" => "",
            "element_label_colon" => TRUE,
            "element_wrapper_type" => "",
            "element_wrapper_class" => "",
            "element_default_classes" => TRUE,
            "empty" => "",
            "hide_empty" => FALSE,
            "empty_zero" => FALSE,
            "hide_alter_empty" => TRUE,
            "type" => "entity_reference_label",
            "settings" => [
              "link" => TRUE,
            ],
          ],
          "field_closing_date" => [
            "id" => "field_closing_date",
            "table" => "node__field_closing_date",
            "field" => "field_closing_date",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "field",
            "label" => "Close Date",
            "exclude" => FALSE,
            "alter" => [
              "alter_text" => FALSE,
              "text" => "",
              "make_link" => FALSE,
              "path" => "",
              "absolute" => FALSE,
              "external" => FALSE,
              "replace_spaces" => FALSE,
              "path_case" => "none",
              "trim_whitespace" => FALSE,
              "alt" => "",
              "rel" => "",
              "link_class" => "",
              "prefix" => "",
              "suffix" => "",
              "target" => "",
              "nl2br" => FALSE,
              "max_length" => 0,
              "word_boundary" => TRUE,
              "ellipsis" => TRUE,
              "more_link" => FALSE,
              "more_link_text" => "",
              "more_link_path" => "",
              "strip_tags" => FALSE,
              "trim" => FALSE,
              "preserve_tags" => "",
              "html" => FALSE,
            ],
            "element_type" => "",
            "element_class" => "",
            "element_label_type" => "",
            "element_label_class" => "",
            "element_label_colon" => TRUE,
            "element_wrapper_type" => "",
            "element_wrapper_class" => "",
            "element_default_classes" => TRUE,
            "empty" => "",
            "hide_empty" => FALSE,
            "empty_zero" => FALSE,
            "hide_alter_empty" => TRUE,
            "type" => "datetime_default",
            "settings" => [
              "timezone_override" => "",
              "format_type" => "short",
            ],
          ],
        ],
        "filters" => [
          "status" => [
            "id" => "status",
            "table" => "node_field_data",
            "field" => "status",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "entity_type" => "node",
            "entity_field" => "status",
            "plugin_id" => "boolean",
            "operator" => "=",
            "value" => "1",
            "group" => 1,
            "exposed" => FALSE,
          ],
          "type" => [
            "id" => "type",
            "table" => "node_field_data",
            "field" => "type",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "entity_type" => "node",
            "entity_field" => "type",
            "plugin_id" => "bundle",
            "operator" => "in",
            "value" => [
              "deal" => "deal",
            ],
            "group" => 1,
            "exposed" => FALSE,
          ],
        ],
        "sorts" => [
          "field_amount_value" => [
            "id" => "field_amount_value",
            "table" => "node__field_amount",
            "field" => "field_amount_value",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "standard",
            "order" => "DESC",
            "expose" => [
              "label" => "",
              "field_identifier" => "",
            ],
            "exposed" => FALSE,
          ],
        ],
        "pager" => [
          "type" => "none",
          "options" => [
            "offset" => 0,
          ],
        ],
        "style" => [
          "type" => "kanban",
          "options" => [
            "grouping" => [
              [
                "field" => "field_stage",
                "rendered" => TRUE,
                "rendered_strip" => FALSE,
              ],
            ],
            "columns" => [],
          ],
        ],
        "row" => [
          "type" => "fields",
        ],
        "query" => [
          "type" => "views_query",
          "options" => [
            "query_comment" => "",
            "disable_sql_rewrite" => FALSE,
            "distinct" => FALSE,
            "replica" => FALSE,
            "query_tags" => [],
          ],
        ],
        "relationships" => [],
        "header" => [],
        "footer" => [],
        "display_extenders" => [],
        "access" => [
          "type" => "perm",
          "options" => [
            "perm" => "access content",
          ],
        ],
        "cache" => [
          "type" => "tag",
          "options" => [],
        ],
        "empty" => [
          "area_text_custom" => [
            "id" => "area_text_custom",
            "table" => "views",
            "field" => "area_text_custom",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "text_custom",
            "empty" => TRUE,
            "content" => "<p>No deals found. <a href=\"/node/add/deal\">Add a deal</a>.</p>",
            "tokenize" => FALSE,
          ],
        ],
      ],
    ],
    "page_1" => [
      "id" => "page_1",
      "display_plugin" => "page",
      "display_title" => "Page",
      "position" => 1,
      "display_options" => [
        "display_extenders" => [],
        "path" => "app/pipeline",
        "menu" => [
          "type" => "normal",
          "title" => "Pipeline",
          "description" => "View deal pipeline kanban board",
          "weight" => 20,
          "expanded" => FALSE,
          "menu_name" => "main",
          "parent" => "",
          "context" => "0",
        ],
      ],
    ],
  ],
]);

$view->save();
echo "✅ Pipeline Kanban view recreated with proper field configuration\n";
echo "✅ field_stage added to fields list for grouping\n";
'

echo ""
echo "🔄 Clearing cache..."
ddev drush cr

echo ""
echo "========================================="
echo "✅ Pipeline Kanban View Fixed!"
echo "========================================="
echo ""
echo "🌐 Test at: http://open-crm.ddev.site/app/pipeline"
echo ""
