#!/bin/bash

###############################################################################
# Script: fix_contacts_view.sh
# Purpose: Fix Contacts view field configuration errors
# Issue: Missing alter and element settings causing TypeError
# Author: DevOps Team
# Date: 2026-02-26
###############################################################################

echo "========================================="
echo "Fixing Contacts View Configuration"
echo "========================================="

ddev drush php-eval '
$view_id = "contacts";

// Delete existing view
$view = \Drupal::entityTypeManager()->getStorage("view")->load($view_id);
if ($view) {
  echo "⚠️  Deleting existing view...\n";
  $view->delete();
}

// Create new view with complete field configurations
$view = \Drupal\views\Entity\View::create([
  "id" => $view_id,
  "label" => "Contacts",
  "description" => "List of all contacts with search filters",
  "tag" => "CRM",
  "base_table" => "node_field_data",
  "display" => [
    "default" => [
      "id" => "default",
      "display_plugin" => "default",
      "display_title" => "Default",
      "position" => 0,
      "display_options" => [
        "title" => "Contacts",
        "fields" => [
          "views_bulk_operations_bulk_form" => [
            "id" => "views_bulk_operations_bulk_form",
            "table" => "views",
            "field" => "views_bulk_operations_bulk_form",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "views_bulk_operations_bulk_form",
            "label" => "",
            "exclude" => FALSE,
            "alter" => [
              "alter_text" => FALSE,
              "text" => "",
              "make_link" => FALSE,
              "path" => "",
              "absolute" => FALSE,
              "external" => FALSE,
              "replace_spaces" => FALSE,
              "path_case" => "none",
              "trim_whitespace" => FALSE,
              "alt" => "",
              "rel" => "",
              "link_class" => "",
              "prefix" => "",
              "suffix" => "",
              "target" => "",
              "nl2br" => FALSE,
              "max_length" => 0,
              "word_boundary" => TRUE,
              "ellipsis" => TRUE,
              "more_link" => FALSE,
              "more_link_text" => "",
              "more_link_path" => "",
              "strip_tags" => FALSE,
              "trim" => FALSE,
              "preserve_tags" => "",
              "html" => FALSE,
            ],
            "element_type" => "",
            "element_class" => "",
            "element_label_type" => "",
            "element_label_class" => "",
            "element_label_colon" => FALSE,
            "element_wrapper_type" => "",
            "element_wrapper_class" => "",
            "element_default_classes" => TRUE,
            "empty" => "",
            "hide_empty" => FALSE,
            "empty_zero" => FALSE,
            "hide_alter_empty" => TRUE,
            "batch" => TRUE,
            "batch_size" => 10,
            "action_title" => "Action",
            "include_exclude" => "exclude",
            "selected_actions" => [],
          ],
          "title" => [
            "id" => "title",
            "table" => "node_field_data",
            "field" => "title",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "entity_type" => "node",
            "entity_field" => "title",
            "plugin_id" => "field",
            "label" => "Name",
            "exclude" => FALSE,
            "alter" => [
              "alter_text" => FALSE,
              "text" => "",
              "make_link" => FALSE,
              "path" => "",
              "absolute" => FALSE,
              "external" => FALSE,
              "replace_spaces" => FALSE,
              "path_case" => "none",
              "trim_whitespace" => FALSE,
              "alt" => "",
              "rel" => "",
              "link_class" => "",
              "prefix" => "",
              "suffix" => "",
              "target" => "",
              "nl2br" => FALSE,
              "max_length" => 0,
              "word_boundary" => TRUE,
              "ellipsis" => TRUE,
              "more_link" => FALSE,
              "more_link_text" => "",
              "more_link_path" => "",
              "strip_tags" => FALSE,
              "trim" => FALSE,
              "preserve_tags" => "",
              "html" => FALSE,
            ],
            "element_type" => "",
            "element_class" => "",
            "element_label_type" => "",
            "element_label_class" => "",
            "element_label_colon" => TRUE,
            "element_wrapper_type" => "",
            "element_wrapper_class" => "",
            "element_default_classes" => TRUE,
            "empty" => "",
            "hide_empty" => FALSE,
            "empty_zero" => FALSE,
            "hide_alter_empty" => TRUE,
            "type" => "string",
            "settings" => [
              "link_to_entity" => TRUE,
            ],
          ],
          "field_organization" => [
            "id" => "field_organization",
            "table" => "node__field_organization",
            "field" => "field_organization",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "field",
            "label" => "Organization",
            "exclude" => FALSE,
            "alter" => [
              "alter_text" => FALSE,
              "text" => "",
              "make_link" => FALSE,
              "path" => "",
              "absolute" => FALSE,
              "external" => FALSE,
              "replace_spaces" => FALSE,
              "path_case" => "none",
              "trim_whitespace" => FALSE,
              "alt" => "",
              "rel" => "",
              "link_class" => "",
              "prefix" => "",
              "suffix" => "",
              "target" => "",
              "nl2br" => FALSE,
              "max_length" => 0,
              "word_boundary" => TRUE,
              "ellipsis" => TRUE,
              "more_link" => FALSE,
              "more_link_text" => "",
              "more_link_path" => "",
              "strip_tags" => FALSE,
              "trim" => FALSE,
              "preserve_tags" => "",
              "html" => FALSE,
            ],
            "element_type" => "",
            "element_class" => "",
            "element_label_type" => "",
            "element_label_class" => "",
            "element_label_colon" => TRUE,
            "element_wrapper_type" => "",
            "element_wrapper_class" => "",
            "element_default_classes" => TRUE,
            "empty" => "",
            "hide_empty" => FALSE,
            "empty_zero" => FALSE,
            "hide_alter_empty" => TRUE,
            "type" => "entity_reference_label",
            "settings" => [
              "link" => TRUE,
            ],
          ],
          "field_phone" => [
            "id" => "field_phone",
            "table" => "node__field_phone",
            "field" => "field_phone",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "field",
            "label" => "Phone",
            "exclude" => FALSE,
            "alter" => [
              "alter_text" => FALSE,
              "text" => "",
              "make_link" => FALSE,
              "path" => "",
              "absolute" => FALSE,
              "external" => FALSE,
              "replace_spaces" => FALSE,
              "path_case" => "none",
              "trim_whitespace" => FALSE,
              "alt" => "",
              "rel" => "",
              "link_class" => "",
              "prefix" => "",
              "suffix" => "",
              "target" => "",
              "nl2br" => FALSE,
              "max_length" => 0,
              "word_boundary" => TRUE,
              "ellipsis" => TRUE,
              "more_link" => FALSE,
              "more_link_text" => "",
              "more_link_path" => "",
              "strip_tags" => FALSE,
              "trim" => FALSE,
              "preserve_tags" => "",
              "html" => FALSE,
            ],
            "element_type" => "",
            "element_class" => "",
            "element_label_type" => "",
            "element_label_class" => "",
            "element_label_colon" => TRUE,
            "element_wrapper_type" => "",
            "element_wrapper_class" => "",
            "element_default_classes" => TRUE,
            "empty" => "",
            "hide_empty" => FALSE,
            "empty_zero" => FALSE,
            "hide_alter_empty" => TRUE,
            "type" => "string",
            "settings" => [
              "link_to_entity" => FALSE,
            ],
          ],
          "field_email" => [
            "id" => "field_email",
            "table" => "node__field_email",
            "field" => "field_email",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "field",
            "label" => "Email",
            "exclude" => FALSE,
            "alter" => [
              "alter_text" => FALSE,
              "text" => "",
              "make_link" => FALSE,
              "path" => "",
              "absolute" => FALSE,
              "external" => FALSE,
              "replace_spaces" => FALSE,
              "path_case" => "none",
              "trim_whitespace" => FALSE,
              "alt" => "",
              "rel" => "",
              "link_class" => "",
              "prefix" => "",
              "suffix" => "",
              "target" => "",
              "nl2br" => FALSE,
              "max_length" => 0,
              "word_boundary" => TRUE,
              "ellipsis" => TRUE,
              "more_link" => FALSE,
              "more_link_text" => "",
              "more_link_path" => "",
              "strip_tags" => FALSE,
              "trim" => FALSE,
              "preserve_tags" => "",
              "html" => FALSE,
            ],
            "element_type" => "",
            "element_class" => "",
            "element_label_type" => "",
            "element_label_class" => "",
            "element_label_colon" => TRUE,
            "element_wrapper_type" => "",
            "element_wrapper_class" => "",
            "element_default_classes" => TRUE,
            "empty" => "",
            "hide_empty" => FALSE,
            "empty_zero" => FALSE,
            "hide_alter_empty" => TRUE,
            "type" => "basic_string",
            "settings" => [],
          ],
          "field_source" => [
            "id" => "field_source",
            "table" => "node__field_source",
            "field" => "field_source",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "field",
            "label" => "Source",
            "exclude" => FALSE,
            "alter" => [
              "alter_text" => FALSE,
              "text" => "",
              "make_link" => FALSE,
              "path" => "",
              "absolute" => FALSE,
              "external" => FALSE,
              "replace_spaces" => FALSE,
              "path_case" => "none",
              "trim_whitespace" => FALSE,
              "alt" => "",
              "rel" => "",
              "link_class" => "",
              "prefix" => "",
              "suffix" => "",
              "target" => "",
              "nl2br" => FALSE,
              "max_length" => 0,
              "word_boundary" => TRUE,
              "ellipsis" => TRUE,
              "more_link" => FALSE,
              "more_link_text" => "",
              "more_link_path" => "",
              "strip_tags" => FALSE,
              "trim" => FALSE,
              "preserve_tags" => "",
              "html" => FALSE,
            ],
            "element_type" => "",
            "element_class" => "",
            "element_label_type" => "",
            "element_label_class" => "",
            "element_label_colon" => TRUE,
            "element_wrapper_type" => "",
            "element_wrapper_class" => "",
            "element_default_classes" => TRUE,
            "empty" => "",
            "hide_empty" => FALSE,
            "empty_zero" => FALSE,
            "hide_alter_empty" => TRUE,
            "type" => "entity_reference_label",
            "settings" => [
              "link" => FALSE,
            ],
          ],
        ],
        "filters" => [
          "status" => [
            "id" => "status",
            "table" => "node_field_data",
            "field" => "status",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "entity_type" => "node",
            "entity_field" => "status",
            "plugin_id" => "boolean",
            "operator" => "=",
            "value" => "1",
            "group" => 1,
            "exposed" => FALSE,
          ],
          "type" => [
            "id" => "type",
            "table" => "node_field_data",
            "field" => "type",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "entity_type" => "node",
            "entity_field" => "type",
            "plugin_id" => "bundle",
            "operator" => "in",
            "value" => [
              "contact" => "contact",
            ],
            "group" => 1,
            "exposed" => FALSE,
          ],
          "title" => [
            "id" => "title",
            "table" => "node_field_data",
            "field" => "title",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "entity_type" => "node",
            "entity_field" => "title",
            "plugin_id" => "string",
            "operator" => "contains",
            "value" => "",
            "group" => 1,
            "exposed" => TRUE,
            "expose" => [
              "operator_id" => "title_op",
              "label" => "Name",
              "description" => "",
              "use_operator" => FALSE,
              "operator" => "title_op",
              "operator_limit_selection" => FALSE,
              "operator_list" => [],
              "identifier" => "title",
              "required" => FALSE,
              "remember" => FALSE,
              "multiple" => FALSE,
              "remember_roles" => [
                "authenticated" => "authenticated",
              ],
              "placeholder" => "Search by name...",
            ],
          ],
          "field_source_target_id" => [
            "id" => "field_source_target_id",
            "table" => "node__field_source",
            "field" => "field_source_target_id",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "taxonomy_index_tid",
            "operator" => "or",
            "value" => [],
            "group" => 1,
            "exposed" => TRUE,
            "expose" => [
              "operator_id" => "field_lead_source_target_id_op",
              "label" => "Source",
              "description" => "",
              "use_operator" => FALSE,
              "operator" => "field_lead_source_target_id_op",
              "operator_limit_selection" => FALSE,
              "operator_list" => [],
              "identifier" => "field_lead_source_target_id",
              "required" => FALSE,
              "remember" => FALSE,
              "multiple" => FALSE,
              "remember_roles" => [
                "authenticated" => "authenticated",
              ],
              "reduce" => FALSE,
            ],
            "type" => "select",
            "limit" => TRUE,
            "vid" => "lead_source",
            "hierarchy" => FALSE,
            "error_message" => TRUE,
          ],
          "field_organization_target_id" => [
            "id" => "field_organization_target_id",
            "table" => "node__field_organization",
            "field" => "field_organization_target_id",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "numeric",
            "operator" => "or",
            "value" => [],
            "group" => 1,
            "exposed" => TRUE,
            "expose" => [
              "operator_id" => "field_organization_target_id_op",
              "label" => "Organization",
              "description" => "",
              "use_operator" => FALSE,
              "operator" => "field_organization_target_id_op",
              "operator_limit_selection" => FALSE,
              "operator_list" => [],
              "identifier" => "field_organization_target_id",
              "required" => FALSE,
              "remember" => FALSE,
              "multiple" => FALSE,
              "remember_roles" => [
                "authenticated" => "authenticated",
              ],
              "reduce" => FALSE,
            ],
          ],
        ],
        "sorts" => [
          "created" => [
            "id" => "created",
            "table" => "node_field_data",
            "field" => "created",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "entity_type" => "node",
            "entity_field" => "created",
            "plugin_id" => "date",
            "order" => "DESC",
            "expose" => [
              "label" => "",
              "field_identifier" => "created",
            ],
            "exposed" => FALSE,
            "granularity" => "second",
          ],
        ],
        "pager" => [
          "type" => "full",
          "options" => [
            "offset" => 0,
            "items_per_page" => 25,
            "total_pages" => NULL,
            "id" => 0,
            "tags" => [
              "next" => "Next ›",
              "previous" => "‹ Previous",
              "first" => "« First",
              "last" => "Last »",
            ],
            "expose" => [
              "items_per_page" => FALSE,
              "items_per_page_label" => "Items per page",
              "items_per_page_options" => "5, 10, 25, 50",
              "items_per_page_options_all" => FALSE,
              "items_per_page_options_all_label" => "- All -",
              "offset" => FALSE,
              "offset_label" => "Offset",
            ],
            "quantity" => 9,
          ],
        ],
        "style" => [
          "type" => "table",
          "options" => [
            "grouping" => [],
            "row_class" => "",
            "default_row_class" => TRUE,
            "columns" => [
              "views_bulk_operations_bulk_form" => "views_bulk_operations_bulk_form",
              "title" => "title",
              "field_organization" => "field_organization",
              "field_phone" => "field_phone",
              "field_email" => "field_email",
              "field_source" => "field_source",
            ],
            "default" => "title",
            "info" => [
              "views_bulk_operations_bulk_form" => [
                "align" => "",
                "separator" => "",
                "empty_column" => FALSE,
                "responsive" => "",
              ],
              "title" => [
                "sortable" => TRUE,
                "default_sort_order" => "asc",
                "align" => "",
                "separator" => "",
                "empty_column" => FALSE,
                "responsive" => "",
              ],
              "field_organization" => [
                "sortable" => TRUE,
                "default_sort_order" => "asc",
                "align" => "",
                "separator" => "",
                "empty_column" => FALSE,
                "responsive" => "",
              ],
              "field_phone" => [
                "sortable" => FALSE,
                "default_sort_order" => "asc",
                "align" => "",
                "separator" => "",
                "empty_column" => FALSE,
                "responsive" => "",
              ],
              "field_email" => [
                "sortable" => FALSE,
                "default_sort_order" => "asc",
                "align" => "",
                "separator" => "",
                "empty_column" => FALSE,
                "responsive" => "",
              ],
              "field_source" => [
                "sortable" => TRUE,
                "default_sort_order" => "asc",
                "align" => "",
                "separator" => "",
                "empty_column" => FALSE,
                "responsive" => "",
              ],
            ],
            "override" => TRUE,
            "sticky" => FALSE,
            "summary" => "",
            "empty_table" => FALSE,
            "caption" => "",
            "description" => "",
          ],
        ],
        "row" => [
          "type" => "fields",
        ],
        "query" => [
          "type" => "views_query",
          "options" => [
            "query_comment" => "",
            "disable_sql_rewrite" => FALSE,
            "distinct" => FALSE,
            "replica" => FALSE,
            "query_tags" => [],
          ],
        ],
        "relationships" => [],
        "header" => [],
        "footer" => [],
        "display_extenders" => [],
        "access" => [
          "type" => "perm",
          "options" => [
            "perm" => "access content",
          ],
        ],
        "cache" => [
          "type" => "tag",
          "options" => [],
        ],
        "empty" => [
          "area_text_custom" => [
            "id" => "area_text_custom",
            "table" => "views",
            "field" => "area_text_custom",
            "relationship" => "none",
            "group_type" => "group",
            "admin_label" => "",
            "plugin_id" => "text_custom",
            "empty" => TRUE,
            "content" => "<p>No contacts found. <a href=\"/node/add/contact\">Add a contact</a>.</p>",
            "tokenize" => FALSE,
          ],
        ],
        "exposed_form" => [
          "type" => "basic",
          "options" => [
            "submit_button" => "Search",
            "reset_button" => TRUE,
            "reset_button_label" => "Reset",
            "exposed_sorts_label" => "Sort by",
            "expose_sort_order" => TRUE,
            "sort_asc_label" => "Asc",
            "sort_desc_label" => "Desc",
          ],
        ],
      ],
    ],
    "page_1" => [
      "id" => "page_1",
      "display_plugin" => "page",
      "display_title" => "Page",
      "position" => 1,
      "display_options" => [
        "display_extenders" => [],
        "path" => "app/contacts",
        "menu" => [
          "type" => "normal",
          "title" => "Contacts",
          "description" => "View and manage contacts",
          "weight" => 10,
          "expanded" => FALSE,
          "menu_name" => "main",
          "parent" => "",
          "context" => "0",
        ],
      ],
    ],
  ],
]);

$view->save();
echo "✅ Contacts view recreated with complete field configurations\n";
'

echo ""
echo "🔄 Clearing cache..."
ddev drush cr

echo ""
echo "========================================="
echo "✅ Contacts View Fixed!"
echo "========================================="
echo ""
echo "🌐 Test at: http://open-crm.ddev.site/app/contacts"
echo ""
