#!/bin/bash

echo "🔐 HƯỚNG DẪN ĐĂNG NHẬP VÀO OPEN CRM"
echo "===================================="
echo ""

echo "📍 URL ĐĂNG NHẬP:"
echo "   http://open-crm.ddev.site/user/login"
echo ""
echo "   (Hoặc click nút 'Log in' ở góc trên bên phải)"
echo ""

echo "👥 TÀI KHOẢN CÓ SẴN:"
echo ""

echo "1️⃣  ADMIN (Full Access)"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Username: admin"
echo "   Password: aa5BLB69Jt"
echo "   Quyền:    Toàn quyền quản trị hệ thống"
echo ""

echo "2️⃣  SALES MANAGER (Xem tất cả data)"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Username: manager"
echo "   Password: manager123"
echo "   Quyền:    Xem tất cả contacts/deals của team"
echo ""

echo "3️⃣  SALES REP 1 (Chỉ xem data của mình)"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Username: salesrep1"
echo "   Password: sales123"
echo "   Data:     Tech Startup ABC, John Doe"
echo ""

echo "4️⃣  SALES REP 2 (Chỉ xem data của mình)"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Username: salesrep2"
echo "   Password: sales123"
echo "   Data:     E-commerce XYZ, Jane Smith"
echo ""

echo "5️⃣  CUSTOMER (Read-only)"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Username: customer1"
echo "   Password: customer123"
echo "   Quyền:    Chỉ xem, không chỉnh sửa"
echo ""

echo "📝 CÁC BƯỚC ĐĂNG NHẬP:"
echo ""
echo "   1. Mở trình duyệt"
echo "   2. Truy cập: http://open-crm.ddev.site"
echo "   3. Click nút 'Log in' (góc trên phải)"
echo "   4. Nhập Username và Password (từ danh sách trên)"
echo "   5. Click 'Log in'"
echo "   6. Bạn sẽ thấy Dashboard với stats cards"
echo ""

echo "💡 GỢI Ý ĐỂ DEMO:"
echo ""
echo "   🎯 Demo Data Privacy:"
echo "   → Đăng nhập bằng salesrep1"
echo "   → Vào /crm/my-contacts"
echo "   → Chỉ thấy 'John Doe (SalesRep1)'"
echo ""
echo "   → Đăng xuất (Log out)"
echo "   → Đăng nhập bằng salesrep2"
echo "   → Vào /crm/my-contacts"
echo "   → Chỉ thấy 'Jane Smith (SalesRep2)'"
echo ""
echo "   → Đăng xuất"
echo "   → Đăng nhập bằng manager"
echo "   → Vào /app/contacts"
echo "   → Thấy TẤT CẢ contacts!"
echo ""

echo "🎨 Demo Giao Diện Đẹp:"
echo "   → Đăng nhập bằng salesrep1"
echo "   → Hover chuột vào Stat Cards (nổi lên)"
echo "   → Hover vào Quick Action buttons"
echo "   → Hover vào rows trong tables (xanh nhạt)"
echo "   → Click Navigation Cards (smooth animation)"
echo ""

echo "🔧 TROUBLESHOOTING:"
echo ""
echo "   ❓ Nếu quên password:"
echo "   → Admin password: aa5BLB69Jt (lưu ý viết đúng chữ hoa/thường)"
echo "   → Sales/Customer: sales123 / manager123 / customer123"
echo ""
echo "   ❓ Nếu không hiện menu:"
echo "   → Clear cache: ddev drush cr"
echo "   → Hoặc refresh trình duyệt (Cmd+Shift+R)"
echo ""
echo "   ❓ Nếu không thấy Dashboard:"
echo "   → URL: http://open-crm.ddev.site"
echo "   → Đảm bảo đã đăng nhập"
echo ""

echo "📋 QUICK COPY:"
echo ""
echo "Admin:      admin / aa5BLB69Jt"
echo "Manager:    manager / manager123"
echo "SalesRep1:  salesrep1 / sales123"
echo "SalesRep2:  salesrep2 / sales123"
echo "Customer:   customer1 / customer123"
echo ""

echo "✨ Hệ thống đã sẵn sàng! Hãy đăng nhập và trải nghiệm!"
